# For help and tutorials, visit https://circleci.com/docs/
# For internal documentation visit https://enturas.atlassian.net/wiki/spaces/ESP/pages/580026490/CircleCI
version: 2.1

orbs:
  node: circleci/node@1.1.6

references:
  workspace_root: &workspace_root
    ~/project
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

aliases:
- &firebase_deploy_dev
  name: Firebase deploy
  command: |
    echo 'export GOOGLE_APPLICATION_CREDENTIALS="$SERVICE_ACCOUNT_DEV"' >> $BASH_ENV
    npx firebase deploy -P dev

jobs:
  build:
    executor:
      name: node/default
      tag: '10.13'
    steps:
    - *attach_workspace
    - checkout
    - node/with-cache:
        cache-key: package-lock.json
        cache-version: v1
        steps:
          - run:
              name: Install dependencies
              command: npm install
    - run:
        name: "Run tests"
        command: npm run test
    - run:
        name: "Create production build"
        command: npm run build
    - persist_to_workspace:
        root: *workspace_root
        paths:
        - .
  deploy-dev:
    executor:
      name: node/default
      tag: '10.13'
    steps:
    - *attach_workspace
    - run: *firebase_deploy_dev

workflows:
  "Build Pipeline":
    jobs:
    - build
    - deploy-dev:
        context: global
        filters:
          branches:
            only: master
        requires:
          - build
